---
title: "RAPID training"
description:
  Training materials created by RAP Implementation and Development team
site:
  distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```
# About this page
This page contains training resources for building Reproducible Analytical Pipelines. They are aimed at Government Analysts wanting to implement best practice into their work. Check out our <b>RAP training in R</b> resources on the top right of the page.
<br><br>
<b> Newly added in July '23:</b>

* Spreadsheet automation in R
<br><br>

In preparation:

* Git training
* Advanced control flow in R
* How to write a good README and more!

# What is RAP and why you should implement it

Reproducible analytical pipelines (RAP) have a range of benefits – from increasing efficiency to improving business continuity.


### How implementing RAP can benefit you and your team? 

**Reduced risks and improved quality**

Lowers the risk of human error, automated checks and audit trail ensure mistakes are never repeated, all of which boost organisation's trustworthiness and reputation. 
You can read more about RAP introduction in the civil service in [Analysis Function strategy](https://analysisfunction.civilservice.gov.uk/policy-store/reproducible-analytical-pipelines-strategy/) and [Goldacre review](https://www.goldacrereview.org/). 

**Increased resilience and business continuity**

Well-documented code stored in accessible location can be used by new analysts with minimal preparation, which makes the team more resilient when people move roles or fall ill. 

**Increased efficiency** 

More time to spend on exploring new ideas or personal development, and less time on copy/pasting and manual checks. 

**Increased collaboration**

Sharing code on Git allows analysts to reuse code between projects, which reduces time to create new analytical pipelines and allows to quickly implement trusted solutions. 

 
